// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// RcppLogisticRegression
List RcppLogisticRegression(NumericVector& Y, NumericMatrix& X, NumericVector& beta);
RcppExport SEXP MHBinaryModelSelection_RcppLogisticRegression(SEXP YSEXP, SEXP XSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector& >::type Y(YSEXP );
        Rcpp::traits::input_parameter< NumericMatrix& >::type X(XSEXP );
        Rcpp::traits::input_parameter< NumericVector& >::type beta(betaSEXP );
        List __result = RcppLogisticRegression(Y, X, beta);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
