# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppLogisticRegression <- function(Y, X, beta) {
    .Call('MHBinaryModelSelection_RcppLogisticRegression', PACKAGE = 'MHBinaryModelSelection', Y, X, beta)
}

